#!/bin/sh
PREPEND_PATH="/Devel/NOVAsom_SDK"
DIRS="Bootloader/u-boot-2014.10-NOVAsom6 Kernel/linux-3.10.17_1.0.2_ga-NOVAsom6 GdsPages/GdsPages FileSystem/AfterCompileCommands Utils"
REPOCOUNT=`echo "$DIRS" | awk '{print NF}'`
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

echo ""
echo "****************************************"
echo "**  Check for locally modified files  **"
echo "****************************************"
echo ""
HERE=`pwd`
COUNTMODS=0
COUNTSENT=0
INCREMENT=1
for i in ${DIRS}; do
        cd /Devel/NOVAsom_SDK/$i
        BASE=`basename $i`
	RESULT=`git status | grep modified`
	if [ "$?" = "0" ]; then
		COUNTMODS=`expr $COUNTMODS + $INCREMENT`;
		echo "${RED}-----> ${BASE} has files modified <-----${NC}"
		echo -n "Do you want to send changes to git repo [Y/n] ? "
		read REPLY
		if [ "${REPLY}" = "Y" ]; then
			echo -n "Enter the text of the modification : "
			read TEXTMOD
			cd ${PREPEND_PATH}/${i}
			#./gitupdate "${TEXTMOD}" >/dev/null 2>&1
			${PREPEND_PATH}/Utils/gitupdate "${TEXTMOD}"
			cd ${HERE} 
			COUNTSENT=`expr $COUNTSENT + $INCREMENT`;
		fi
	else
		echo "${GREEN}SYNC OK${NC} : ${BASE}"
	fi
done
echo ""
echo "Finished. Found ${RED}${COUNTMODS}${NC} modification(s) , ${RED}${COUNTSENT}${NC} file(s) sent to remote from ${GREEN}${REPOCOUNT}${NC} local repos"
echo ""
